
spring:
  jpa:
    show-sql: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/gdc_person
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    
eureka:
  client:
    enabled : true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  #instance:
    #instance-id: ${spring.application.name}-${server.port}
    #hostname: localhost
      
logging:
  config: classpath:./logback-spring.xml
  
log:
  path: D:/var/logs/${spring.application.name}
  level:
    root: INFO
    gdc: TRACE
