server:
  port: 8184
  
spring:
  application:
    name: gdc-taxi-service
  jpa:
    show-sql: true
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/gdc_taxi
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    
eureka:
  client:
    enabled : true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
      
logging:
  config: classpath:./logback-spring.xml
  
log:
  path: D:/var/logs/${spring.application.name}
  level:
    root: INFO
    gdc: TRACE
    api: TRACE
    
gdc:
  cache:
    redis:
      server: 127.0.0.1
      port: 6379
      password: 0